import boto3

region = "us-east-1"
pr_name = "Chimborazo"
dynamodb = boto3.Session(region_name=region, profile_name=pr_name).resource("dynamodb")

def put_item(tableName, item):
    dynamodb.Table(tableName).put_item(Item=item)

if __name__ == "__main__":
    tableName = "qa-usrv-hierarchy-core"
    # Case 1 -- All nodes same country and from and to nodes are transactional
    items = [{
        "nodeId": "1",
        "rootId": "1",
        "rulesId": "dsfsdfeewe",
        "tarifsId": "223323",
        "path": "1",
        "countryCode": "EC200",
        "status": "active",
        "nodeType": "1",
        "processorsId": "455464654",
        "billingId": "3443434",
        "name": "Alan test",
        "keysId": "dfsdfssdfs",
        "deffersId": "12121213",
        "dispersionId": "21312313",
        "description": "Gabriel",
        "merchantId": "1",
        "costsId": "ewrwerewerew"
        },
        {
        "nodeId": "2",
        "rootId": "1",
        "rulesId": "dsfsdfeewe",
        "tarifsId": "223323",
        "path": "1:2",
        "countryCode": "EC200",
        "status": "active",
        "nodeType": "1",
        "processorsId": "455464654",
        "billingId": "3443434",
        "name": "Alan test",
        "keysId": "dfsdfssdfs",
        "deffersId": "12121213",
        "dispersionId": "21312313",
        "description": "Gabriel",
        "merchantId": "2",
        "costsId": "ewrwerewerew"
        },
        {
        "nodeId": "3",
        "rootId": "1",
        "rulesId": "dsfsdfeewe",
        "tarifsId": "223323",
        "path": "1:3",
        "countryCode": "EC200",
        "status": "active",
        "nodeType": "1",
        "processorsId": "455464654",
        "billingId": "3443434",
        "name": "Alan test",
        "keysId": "dfsdfssdfs",
        "deffersId": "12121213",
        "dispersionId": "21312313",
        "description": "Gabriel",
        "merchantId": "3",
        "costsId": "ewrwerewerew"
        },
        {
        "nodeId": "4",
        "rootId": "1",
        "rulesId": "dsfsdfeewe",
        "tarifsId": "223323",
        "path": "1:3:4",
        "countryCode": "EC200",
        "status": "active",
        "nodeType": "1",
        "processorsId": "455464654",
        "billingId": "3443434",
        "name": "Alan test",
        "keysId": "dfsdfssdfs",
        "deffersId": "12121213",
        "dispersionId": "21312313",
        "description": "Gabriel",
        "merchantId": "4",
        "costsId": "ewrwerewerew"
        },

        {
        "nodeId": "5",
        "rootId": "1",
        "rulesId": "dsfsdfeewe",
        "tarifsId": "223323",
        "path": "1:3:5",
        "countryCode": "EC200",
        "status": "active",
        "nodeType": "1",
        "processorsId": "455464654",
        "billingId": "3443434",
        "name": "Alan test",
        "keysId": "dfsdfssdfs",
        "deffersId": "12121213",
        "dispersionId": "21312313",
        "description": "Gabriel",
        "merchantId": "5",
        "costsId": "ewrwerewerew"
        },
        {
        "nodeId": "6",
        "rootId": "1",
        "rulesId": "dsfsdfeewe",
        "tarifsId": "223323",
        "path": "1:3:5:6",
        "countryCode": "EC200",
        "status": "active",
        "nodeType": "1",
        "processorsId": "455464654",
        "billingId": "3443434",
        "name": "Alan test",
        "keysId": "dfsdfssdfs",
        "deffersId": "12121213",
        "dispersionId": "21312313",
        "description": "Gabriel",
        "merchantId": "6",
        "costsId": "ewrwerewerew"
        },
        {
        "nodeId": "7",
        "rootId": "1",
        "rulesId": "dsfsdfeewe",
        "tarifsId": "223323",
        "path": "1:2:7",
        "countryCode": "EC200",
        "status": "active",
        "nodeType": "1",
        "processorsId": "455464654",
        "billingId": "3443434",
        "name": "Alan test",
        "keysId": "dfsdfssdfs",
        "deffersId": "12121213",
        "dispersionId": "21312313",
        "description": "Gabriel",
        "merchantId": "7",
        "costsId": "ewrwerewerew"
        }
    ]

    # Case 2 -- When targetNode is noTransactional an fromNode is transactional
    
    # items = [{
    #     "nodeId": "1",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "2",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "2",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:2",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "2",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "3",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "4",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3:4",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },

    #     {
    #     "nodeId": "5",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3:5",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "6",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3:5:6",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "7",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:2:7",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     }
    # ]

    # Case 3 --- target node is Transactional an from node is no transactional

    # items = [{
    #     "nodeId": "1",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "2",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "2",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:2",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "3",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "2",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "4",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3:4",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },

    #     {
    #     "nodeId": "5",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3:5",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "6",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3:5:6",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "7",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:2:7",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     }
    # ]

    # Case 4 -- fromNode and targetNode are transactional but country is different

    # items = [{
    #     "nodeId": "1",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "2",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:2",
    #     "countryCode": "EC2001",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "3",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "4",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3:4",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },

    #     {
    #     "nodeId": "5",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3:5",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "6",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3:5:6",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "7",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:2:7",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     }
    # ]


    # Case 5 -- target and from node are not transactional

    # items = [{
    #     "nodeId": "1",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "2",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:2",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "2",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "3",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "2",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "4",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3:4",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },

    #     {
    #     "nodeId": "5",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3:5",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "6",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:3:5:6",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     },
    #     {
    #     "nodeId": "7",
    #     "rootId": "1",
    #     "rulesId": "dsfsdfeewe",
    #     "tarifsId": "223323",
    #     "path": "1:2:7",
    #     "countryCode": "EC200",
    #     "status": "active",
    #     "nodeType": "1",
    #     "processorsId": "455464654",
    #     "billingId": "3443434",
    #     "name": "Alan test",
    #     "keysId": "dfsdfssdfs",
    #     "deffersId": "12121213",
    #     "dispersionId": "21312313",
    #     "description": "Gabriel",
    #     "merchantId": "2323232323",
    #     "costsId": "ewrwerewerew"
    #     }
    # ]

    for item in items:
        put_item(tableName, item)